In [1]:
import numpy as np

In [3]:
arr = np.arange(11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [7]:
A = np.random.rand(10)
A

array([0.00550151, 0.2151674 , 0.35548484, 0.63216385, 0.44459708,
       0.25894661, 0.83182342, 0.72540573, 0.36789444, 0.42976121])

In [8]:
B = np.random.rand(10)
B

array([0.58759019, 0.32505033, 0.59193581, 0.03856128, 0.49548961,
       0.30514667, 0.44681251, 0.76383805, 0.84154695, 0.12271791])

In [9]:
np.add(A, B)

array([0.5930917 , 0.54021773, 0.94742065, 0.67072513, 0.9400867 ,
       0.56409328, 1.27863594, 1.48924378, 1.2094414 , 0.55247912])

In [10]:
np.maximum(A, B)

array([0.58759019, 0.32505033, 0.59193581, 0.63216385, 0.49548961,
       0.30514667, 0.83182342, 0.76383805, 0.84154695, 0.42976121])