In [1]:
import numpy as np

In [2]:
mylist1 = [1,2,3,4,5]

In [3]:
myarray1 = np.array(mylist1)

In [4]:
myarray1

array([1, 2, 3, 4, 5])

In [5]:
mylist2 = [11,22,33,44,55]

In [6]:
mylists = [mylist1, mylist2]

In [7]:
myarray2 = np.array(mylists)

In [8]:
myarray2

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [10]:
myarray2.shape

(2, 5)

In [11]:
myarray2.dtype

dtype('int64')

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(5, 50 , 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])